# Generated by Django 3.2.5 on 2021-07-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='picture',
            field=models.ImageField(null=True, upload_to='job_pics/'),
        ),
    ]
