# Generated by Django 3.2.5 on 2021-07-31 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_date_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carpenter',
            new_name='Worker',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='carpenter',
            new_name='Worker',
        ),
    ]
